### PR TITLE
Fixed failure to export files to desktop path on windows

### PR DESCRIPTION
**Pull request by FreeGoStudio**
Fixed failure to export files to desktop path on windows

### CODE REVIEW

**Comment by NathanSweet** [comment]
Thanks, but even without this change I see absolute paths working correctly. When it doesn't work for you, what are the values you see for `absolute` and `decodeURI(new File("child").parent.fsName)`?
即使不进行这次更改，我也发现绝对路径工作正常。当它对你不起作用时，你看到的 `absolute` 和 `decodeURI(new File("child").parent.fsName)` 的值是什么？

**Comment by FreeGoStudio** [comment]
I added two lines of output:
```js
function absolutePath (path) {
	path = forwardSlashes(trim(path));
	if (!startsWith(path, ".") && !startsWith(path, "~")) {
		var absolute = decodeURI(new File(path).fsName);
		alert("absolute:\n"+absolute);
		alert("child:\n"+decodeURI(new File("child").parent.fsName));
		if (!startsWith(absolute, decodeURI(new File("child").parent.fsName)) ) return forwardSlashes(absolute) + "/";
		path = "./" + path;
	}
	if (path.length == 0)
		path = decodeURI(activeDocument.path);
	else if (startsWith(path, "./"))
		path = decodeURI(activeDocument.path) + path.substring(1);
	path = (new File(path).fsName).toString();
	path = forwardSlashes(path);
	if (path.substring(path.length - 1) != "/") path += "/";
	return path;
}
```

The input values for the test are:
```
C:\Users\hack7\Desktop\a
```

The `absolute` values is:
```
C:\Users\hack7\Desktop\a
```

Photoshop_5sNe0ljeAJ


The `decodeURI(new File("child").parent.fsName)` is:
```
C:\Users\hack7\Desktop
```

Photoshop_hKOgcV0trt

So, `!startsWith(absolute, decodeURI(new File("child").parent.fsName))` is false.

Photoshop_K11LanHGhx

Thanks, my english is poor, please forgive me.

**Comment by FreeGoStudio** [comment]
> 谢谢，但即使没有这种改变，我也看到绝对路径工作正常。当它对你不起作用时，你看到的值是什么`absolute`？`decodeURI(new File("child").parent.fsName)`即使 这次不进行更改，我也发现绝对路径工作正常。当它对你失效时，你看到的`absolute`值`decodeURI(new File("child").parent.fsName)`是什么？



> 谢谢，但即使没有这种改变，我也发现绝对路径工作正常。当它对你禁用时，你的值是什么`absolute`？`decodeURI(new File("child").parent.fsName)`即使 这次不进行更改，我也发现绝对路径工作正常。当它对你失效时，你看到的`absolute`价值`decodeURI(new File("child").parent.fsName)`是什么？

I added two lines of output:
```js
function absolutePath (path) {
	path = forwardSlashes(trim(path));
	if (!startsWith(path, ".") && !startsWith(path, "~")) {
		var absolute = decodeURI(new File(path).fsName);
		alert("absolute:\n"+absolute);
		alert("child:\n"+decodeURI(new File("child").parent.fsName));
		if (!startsWith(absolute, decodeURI(new File("child").parent.fsName)) ) return forwardSlashes(absolute) + "/";
		path = "./" + path;
	}
	if (path.length == 0)
		path = decodeURI(activeDocument.path);
	else if (startsWith(path, "./"))
		path = decodeURI(activeDocument.path) + path.substring(1);
	path = (new File(path).fsName).toString();
	path = forwardSlashes(path);
	if (path.substring(path.length - 1) != "/") path += "/";
	return path;
}
```

The input values for the test are:
```
C:\Users\hack7\Desktop\a
```

The `absolute` values is:
```
C:\Users\hack7\Desktop\a
```

Photoshop_5sNe0ljeAJ


The `decodeURI(new File("child").parent.fsName)` is:
```
C:\Users\hack7\Desktop
```

Photoshop_hKOgcV0trt

So, `!startsWith(absolute, decodeURI(new File("child").parent.fsName))` is false.

Photoshop_K11LanHGhx

Thanks, my english is poor, please forgive me.

**Comment by NathanSweet** [comment]
Thanks! I think the intended code is this:
```
if (!startsWith(absolute, decodeURI(new File(activeDocument.path).fsName))) return forwardSlashes(absolute) + "/";
```
If the path interpreted as an absolute path does not start with the path to the PSD, then use it as an absolute path.

It's a bit more complex than we really need though. Also it is not really useful to use the path as an absolute path when it does not start with a drive letter or slash. For example, `images` as an absolute path will use the Photoshop working directory (usually where Photoshop is installed) + `images`, which is never what a user wants

 Given that, I think a solution similar to what you propose is better than checking the path for a prefix. If a path has no drive letter and does not start with a slash, we should consider it relative to the PSD.

**Comment by NathanSweet** [comment]
Also your English is perfectly fine. It's my Chinese that is poor!

**Comment by NathanSweet** [comment]
Can you please try the fix in v7.36? If it doesn't work we'll reopen this issue.

Thanks for your help to improve the script!

**Comment by FreeGoStudio** [comment]
> Can you please try the fix in v7.36? If it doesn't work we'll reopen this issue.
> 
> Thanks for your help to improve the script!

I tested  v7.36, it worked fine, Thanks.

**Pull request closed without merging**
